This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Fontana_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Fontana_thesis.acn....done (281 entries accepted, 0 rejected).
Sorting entries.....done (2596 comparisons).
Generating output file Fontana_thesis.acr....done (146 lines written, 0 warnings).
Output written in Fontana_thesis.acr.
Transcript written in Fontana_thesis.alg.
